[package]
name = "rust-payments-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
log = "0.4.28"
env_logger = "0.11.8"
rust_decimal = { version = "1.39.0", features = ["macros"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
